### ISSUE TITLE
How to Add and Remove Elements from Arrays in JavaScript

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#11]
https://www.freecodecamp.org/news/how-to-add-and-remove-js-array-elements/

**Comment by LucasAMoralesRomero** [comment]
Good morning, @RafaelDavisH, please assign me this article.
Best regards.

Lucas A. Morales

**Comment by LucasAMoralesRomero** [comment]
Good afternoon @RafaelDavisH , tomorrow I will begin the translation. Based on my work schuddle for this week, the estimated time to complete this task is next Wednesday, the 24th.
Best regards.
Lucas A. Morales

**Comment by RafaelDavisH** [comment]
Good evening, @LucasAMoralesRomero. I appreciate how you always keep us in the loop with where you're at in the translation process.

Cheers,

**Comment by LucasAMoralesRomero** [comment]
Good morning @RafaelDavisH ,I have completed the translation. Here is the link: https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/661b0d331238a40479c58e93.
This time, I rewrote the article to strive for a more universal tone. As always, if you have any suggestions, please send me a message or respond to this issue.
Best regards,
Lucas A. Morales
