### ISSUE TITLE
Client-Side Form Handling with JavaScript – Explained with Example Code

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#12]
https://www.freecodecamp.org/news/form-validation-in-javascript/

**Comment by Octaviusb** [comment]
Hi, assign me this project, please, explain to me procedure

**Comment by RafaelDavisH** [comment]
Hi Ener, 

This article is now assigned to you @Octaviusb. You have the link above to the original English article for reference. Log in to [Ghost](https://freecodecamp.org/espanol/news/ghost) and begin translating whenever you are ready.

Once, the translation is complated, go ahead and comment here, "ready for revision" and I'll the card for revision. 

That's all. You're free to choose another article to translate whenever you want.

Thank you for your contributions  🙏
