### ISSUE TITLE
SVG Toggle Button Tutorial – How to Handle Dark Mode with CSS and JavaScript

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#13]
https://www.freecodecamp.org/news/how-to-handle-dark-mode-with-css-and-javascript/

**Comment by Octaviusb** [comment]
ready for review
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/661e84d21238a40479c592c1

**Comment by RafaelDavisH** [comment]
@Octaviusb, gracias por la traducción de este artículo 🙏. 

Parece que no se te había asignado o no solicitaste que se te asignara con anticipación. Nos alegra que lo hayas traducido, solo por favor, solicita que se te asigne antes de traducirlo 🙏.

Gracias nuevamente por la traducción

**Comment by Octaviusb** [comment]
perdon, lo siento, mis disculpas, me atrevi a traducirlo en virtud de que en el correo que me enviaste con relacion a la adjudicación del anterior, me parecio entender que me dabas libertad para abordar cualquier otro tema.
No obstante reitero mis disculpas, y prometo no volver a asumir sin permiso


Octavio Buitrago Camelo

 

    En martes, 16 de abril de 2024, 10:59:46 GMT-5, Rafael D. Hernandez ***@***.***> escribió:  
 
 


@Octaviusb, gracias por la traducción de este artículo 🙏.

Parece que no se te había asignado o no solicitaste que se te asignara con anticipación. Nos alegra que lo hayas traducido, solo por favor, solicita que se te asigne antes de traducirlo 🙏.

Gracias nuevamente por la traducción

**Comment by RafaelDavisH** [comment]
No te preocupes. Gracias 🙏
