### ISSUE TITLE
How to Access Properties from an Array of Objects in JavaScript

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#14]
https://www.freecodecamp.org/news/how-to-access-properties-from-an-array-of-objects-in-javascript/

**Comment by geekcoty** [comment]
Assign this article to me.

**Comment by geekcoty** [comment]
Ready for review
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/6643b40b66e68c03ffefd7e5
