### ISSUE TITLE
25 Python Projects for Beginners – Easy Ideas to Get Started Coding Python

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news-translation-tasks#183]
https://www.freecodecamp.org/news/python-projects-for-beginners/

**Comment by YUUSUKE18** [comment]
@sidemt 

レビューお願いします。
久しぶりなので、ガンガン指摘してください！

**Comment by YUUSUKE18** [comment]
@sidemt 

レビュー ありがとうございます！

＞の前半と後半がうまく対応していないところが見受けられたので、次回気を付けて見ていただけたら助かります🙇‍♂️

所々、補足するとかなりの分量になり、削除したのが、よくなかったですね。
以後気をつけます！
