### ISSUE TITLE
How to Update Node and NPM to the Latest Version

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news-translation-tasks#190]
https://www.freecodecamp.org/news/how-to-update-node-and-npm-to-the-latest-version/

**Comment by Terafora** [comment]
@sidemt この記事の翻訳を取ってよろしいですか？🙂

**Comment by Terafora** [comment]
この記事の翻訳を終えました。レビューに回す前に、数日間待ってから自己レビューを行います。

**Comment by Terafora** [comment]
@sidemt フィードバックをありがとうございます。

修正をお送りするのに時間がかかってしまい、申し訳ありません。7月末に手術を予定しており、その準備で急に忙しくなってしまいました。😅
