### ISSUE TITLE
How to Convert a String to a Number in JavaScript

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news-translation-tasks#191]
https://www.freecodecamp.org/news/how-to-convert-a-string-to-a-number-in-javascript/

**Comment by Terafora** [comment]
こんにちは @sidemt様。お疲れ様で〜す。　
申し訳ありませんが、作成されたフォーマットツールのリンクを再送していただけますか？OSを変更したので、もうリンクが見つかりません。🙏

**Comment by Terafora** [comment]
@sidemt はい、ありがとうございました。🙂
頑張りましょう!

**Comment by Terafora** [comment]
新しいワークフローを確認して、これからそれに従いますね。もし迷惑かけてたらごめんなさい！🙇‍♀️
