### ISSUE TITLE
Bash Scripting Tutorial – Linux Shell Script and Command Line for Beginners

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news-translation-tasks#195]
https://www.freecodecamp.org/news/bash-scripting-tutorial-linux-shell-script-and-command-line-for-beginners/

**Comment by Terafora** [comment]
記事の翻訳を終え、すべての内部リンクを追加し、フォーマッターを使用しました。
明日もう一度読み返してからレビューに出します。
時間がかかってしまい申し訳ありません。🙏
