### ISSUE TITLE
How to Use the JavaScript Map and Set Objects – Explained with Code Examples

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#20]
https://www.freecodecamp.org/news/javascript-map-and-set-objects-explained/

**Comment by RafaelDavisH** [comment]
Excelente @EliasPereyra  - Gracias 🙏

**Comment by EliasPereyra** [comment]
De nada @RafaelDavisH ha sido un gusto!
