### ISSUE TITLE
JavaScript Refresh Page – How to Reload a Page in JS

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news-translation-tasks#204]
https://www.freecodecamp.org/news/javascript-refresh-page-how-to-reload-a-page-in-js/

**Comment by Terafora** [comment]
@sidemt お疲れ様です～ 😄 

この記事の翻訳の初回チェックを行い、途中で文法を確認してきましたが、最後の文「Happy Coding!」について一つ確認したいことがあります。それを日本語訳と一緒に含めましたが、最後の文は英語のみ、または日本語のみで表示するのが良いでしょうか？ 🤔 

数日後に自分で記事をもう一度読み直し、より良い編集ができるようにします。その後、さらにレビューのために送る前に上記の変更を行います。

**Comment by Terafora** [comment]
@sidemt こんにちは、こちらこそお世話になっております。
はい、その X アカウントにタグ付けしてください。

来週の月曜日に手術があるため、数ヶ月間翻訳作業をお休みします。回復に時間がかかる見込みです。

夏の残りを楽しんで、またお話ししましょう。😊
