### ISSUE TITLE
How Types Work in TypeScript – Explained with JavaScript + TypeScript Code

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#23]
https://www.freecodecamp.org/news/basic-typescript-types/

**Comment by RafaelDavisH** [comment]
Gracias @crisdux por la traducción - 🏆

**Comment by crisdux** [comment]
Muchas gracias a ti @RafaelDavisH, siempre encantado de poder colaborar en la comunidad
