### ISSUE TITLE
How to Build a Dropdown Menu with JavaScript

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#240]
https://www.freecodecamp.org/news/how-to-build-a-dropdown-menu-with-javascript/

**Comment by geekcoty** [comment]
Assign this article to me.

**Comment by RafaelDavisH** [comment]
Gracias, @geekcoty 

También, puedes usar el comando `/translate` para asignarte el artículo que deseas traducir.

**Comment by geekcoty** [comment]
¡Genial, gracias!

From: Rafael D. Hernandez ***@***.***>
Date: Tuesday, 9 July 2024 at 10:28
To: freeCodeCamp/news-translation-tasks ***@***.***>
Cc: Coty ***@***.***>, Mention ***@***.***>
Subject: Re: [freeCodeCamp/news-translation-tasks] How to Build a Dropdown Menu with JavaScript (Issue #240)

Gracias, @geekcoty<https://github.com/geekcoty>

También, puedes usar el comando /translate para asignarte el artículo que deseas traducir.

**Comment by geekcoty** [comment]
Ready for review:
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/66913863b99552046f705ccc

**Comment by RafaelDavisH** [comment]
Gracias @geekcoty por la traducción 🚀
