### ISSUE TITLE
How to Build an Image Carousel with React and Framer Motion

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#250]
https://www.freecodecamp.org/news/build-an-image-carousel-with-react-and-framer-motion/

**Comment by geekcoty** [comment]
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/66f4465c7985df0457eb175c

**Comment by EliasPereyra** [comment]
Muchas gracias por la traducción 🚀
