### ISSUE TITLE
How to Fetch Data in React: Cheat Sheet + Examples

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#255]
https://www.freecodecamp.org/news/fetch-data-react/

**Comment by juancguana** [comment]
"Assign this article to me."

**Comment by juancguana** [comment]
Hello @RafaelDavisH , 
ready for revision
https://www.freecodecamp.org/espanol/news/p/c5a7ba1c-014e-4f6b-89bf-fc3c603e914d/

**Comment by RafaelDavisH** [comment]
Gracias @juancguana por la traducción
