### ISSUE TITLE
10 to the Power of 0: the Zero Exponent Rule and the Power of Zero Explained

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#263]
https://www.freecodecamp.org/news/10-to-the-power-of-0-the-zero-exponent-rule-and-the-power-of-zero-explained/

**Comment by a-then** [comment]
/review

Please, let me know if I need to change anything to comply with FCC and its l10n efforts.

**Comment by RafaelDavisH** [comment]
Thank you @a-then for your translation. Revised and published.
