### ISSUE TITLE
Python String to Array – How to Convert Text to a List

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#271]
https://www.freecodecamp.org/news/python-string-to-array-how-to-convert-text-to-a-list/
https://www.freecodecamp.org/italian/news/ghost/#/editor/post/66824c83b3d5b00437d67789

**Comment by aedoardo1990** [comment]
Ciao Andrea! Ho appena finito di tradurre l'articolo, se hai domande, non esitare a chiedere

**Comment by Dario-DC** [comment]
Grazie per il tuo contributo @aedoardo1990 L'articolo sarà live tra qualche ora :tada:

**Comment by aedoardo1990** [comment]
Ottimo :) grazie a te @Dario-DC per il supporto e la collaborazione!
