### ISSUE TITLE
Check if an Item is in an Array in JavaScript – JS Contains with Array.includes()

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#272]
https://www.freecodecamp.org/news/check-if-an-item-is-in-an-array-in-javascript-js-contains-with-array-includes/

**Comment by LucasAMoralesRomero** [comment]
12/04 - I finished the translation, this is the draft: https://www.freecodecamp.org/espanol/news/p/2fe0dc84-00d9-4f76-8d12-38a584c45999/, the suggested title in spanish could be: "Comprobar si un elemento está presente en un arreglo en JavaScript utilizando el método Array.includes()". As always if you have any suggest, please send me a message or answer over this issue. - Lucas A. Morales

**Comment by RafaelDavisH** [comment]
El título es un poco estrategia para SEO. No todo tiempo se llega a entender al traducirse.

 Gracias Lucas 🙏
