### ISSUE TITLE
How to Build Your Very First Python Package

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#274]
https://www.freecodecamp.org/news/build-your-first-python-package/

**Comment by Dario-DC** [comment]
Grazie per il tuo primo contributo @Andrea-Sisti 
L'ho appena pubblicato :tada:

**Comment by Andrea-Sisti** [comment]
Ciao Dario,

grazie mille a te!
A presto,

Andrea

Il giorno ven 28 giu 2024 alle ore 15:21 Dario-DC ***@***.***>
ha scritto:
