### ISSUE TITLE
How to Create and Sync Git and GitHub Repositories

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#276]
https://www.freecodecamp.org/news/create-and-sync-git-and-github-repositories/

**Comment by RafaelDavisH** [comment]
@crisdux, excelente traducción y gracias por agregar la nota.

**Comment by crisdux** [comment]
Gracias a ti estimado @Rafael D. Hernandez ***@***.***>, un
saludo!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Libre
de virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
