### ISSUE TITLE
How to Get Started in Data Analytics – A Roadmap for Beginners

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#279]
https://www.freecodecamp.org/news/data-analytics-roadmap/

**Comment by geekcoty** [comment]
Ready for Review
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/65ecde44e41e0704006c192c

**Comment by RafaelDavisH** [comment]
Thank you @geekcoty
