### ISSUE TITLE
How to Check Internet Connection Status Using Async JavaScript

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#282]
https://www.freecodecamp.org/news/how-to-check-internet-connection-status-with-javascript/
https://www.freecodecamp.org/italian/news/ghost/#/editor/post/668292aab3d5b00437d67b4c

**Comment by Dario-DC** [comment]
Grazie Andrea, l'ho appena pubblicato.

**Comment by Andrea-Sisti** [comment]
Ciao Dario, grazie a te, a presto

Il lun 8 lug 2024, 17:35 Dario-DC ***@***.***> ha scritto:
