### ISSUE TITLE
C++ Vector – How to Initialize a Vector in a Constructor in C++

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#283]
https://www.freecodecamp.org/news/cpp-vector-how-to-initialize-a-vector-in-a-constructor/

**Comment by LucasAMoralesRomero** [comment]
I finished the translation, this is the draft: https://www.freecodecamp.org/espanol/news/p/046b19ed-f789-4c82-85fe-df8cd3244e1c/, the suggested title is "Vectores en C++ - Cómo inicializar un vector utilizando el constructor de una clase". If you have any suggest about the article, please send me a message or answer over this issue.
Lucas A. Morales

**Comment by RafaelDavisH** [comment]
Thanks @LucasAMoralesRomero 

Great title suggestion. Small modification to make a bit clearer what the article covers (in general) and for SEO purposes (having C++ twice).
- "Vectores en C++: Cómo inicializar un vector en un constructor en C++"

Revised and published 🚀
