### ISSUE TITLE
What is Recursion? A Recursive Function Explained with JavaScript Code Examples

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#284]
https://www.freecodecamp.org/news/what-is-recursion-in-javascript/

https://www.freecodecamp.org/italian/news/ghost/#/editor/post/661b3a1daedb4204c0d38dc6

**Comment by anprivitera** [comment]
Questo lo posso commentare io :)

**Comment by anprivitera** [comment]
Ciao Dario, ho finito di tradurre l'articolo. Fammi sapere se hai domande!

**Comment by Dario-DC** [comment]
Ciao Andrea, ho cambiato giusto qualche frase e l'ho appena pubblicato. Grazie per il tuo contributo :tada:
