### ISSUE TITLE
Asynchronous JavaScript – Callbacks, Promises, and Async/Await Explained

### ISSUE THREAD

**Issue by sidemt** [freeCodeCamp/news-translation-tasks#285]
https://www.freecodecamp.org/news/asynchronous-javascript-explained/

Copied from: https://trello.com/c/4ymQfibi

**Comment by yukiyohure** [comment]
/review
https://www.freecodecamp.org/japanese/news/ghost/#/editor/post/65e555331059c803f19b4803

**Comment by yukiyohure** [comment]
@sidemt 
レビューありがとうございました！
なかなか活動できずすみません... 牛歩ですがこれからも貢献できればと思います。

Discord見れてなかったので確認してみます！！
