### ISSUE TITLE
The C Beginner's Handbook: Learn C Programming Language basics in just a few hours

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#286]
https://www.freecodecamp.org/news/the-c-beginners-handbook/

**Comment by palmaone** [comment]
Hola Rafa me gustaría hacer la revisión de este artículo

**Comment by palmaone** [comment]
Hola Rafa 👋🏽😃 oye tengo una duda acerca de este artículo. 

Estoy un poco confundido 🤔 ya que parece que aún no está completa la traducción, pero el artículo ya se encuentra en estatus de revision. 

Podrías indicarme si puedo terminar la traducción (lo haría con mucho gusto) o debería esperar a que terminen de traducirlo (no sé quién lo esté realizando).

**Comment by RafaelDavisH** [comment]
@palmaone, Gracias. Sí, por favor, si lo puedes terminar. Esta traducción fue hecha en un documento Google y después transferido a Ghost.  Así que le falta muchos detalles.

**Comment by RafaelDavisH** [comment]
Gracias @palmaone por terminar la traducción de este manual 🙏

**Comment by palmaone** [comment]
Un placer Rafa gracias a ustedes 🙌🏽
