### ISSUE TITLE
Git Switch Branch – How to Change the Branch in Git

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#288]
https://www.freecodecamp.org/news/git-switch-branch/
https://www.freecodecamp.org/italian/news/ghost/#/editor/post/671fc1029ae93404d0694211

**Comment by Dario-DC** [comment]
Grazie @Andrea-Sisti l'ho appena pubblicato!

**Comment by Andrea-Sisti** [comment]
Grazie a te, Dario, a presto!

Il ven 13 dic 2024, 11:01 Dario-DC ***@***.***> ha scritto:
