### ISSUE TITLE
How to Convert a String to a Number in JavaScript

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#293]
https://www.freecodecamp.org/news/how-to-convert-a-string-to-a-number-in-javascript/
https://www.freecodecamp.org/italian/news/ghost/#/editor/post/67192945a104b2047224803f

**Comment by Dario-DC** [comment]
Grazie @Andrea-Sisti l'ho appena pubblicato 🎉

**Comment by Andrea-Sisti** [comment]
Grazie a te, Dario, a presto!

Il sab 2 nov 2024, 11:57 Dario-DC ***@***.***> ha scritto:
