### ISSUE TITLE
JavaScript Split – How to Split a String into an Array in JS

### ISSUE THREAD

**Issue by Dario-DC** [freeCodeCamp/news-translation-tasks#296]
https://www.freecodecamp.org/news/javascript-split-how-to-split-a-string-into-an-array-in-js/
https://www.freecodecamp.org/italian/news/ghost/#/editor/post/671a0e16a104b204722481e5

**Comment by Andrea-Sisti** [comment]
Grazie a te, Dario, a presto!

Il lun 4 nov 2024, 10:46 Dario-DC ***@***.***> ha scritto:
