### ISSUE TITLE
Learn Foundational Mathematics on freeCodeCamp – Interactive Math Courses Open Beta

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#310]
https://www.freecodecamp.org/news/freecodecamp-foundational-math-curriculum/

**Comment by franciscomelov** [comment]
Assign this article to me.
Hi, I'd like to translate this article.

**Comment by franciscomelov** [comment]
Hi, I completed the article, 
here is the link
https://www.freecodecamp.org/espanol/news/p/04b9e8d8-6499-4a19-8272-a0d60950dc76/
thanks
