### ISSUE TITLE
Statistics for Data Science — a Complete Guide for Aspiring ML Practitioners

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#311]
https://www.freecodecamp.org/news/statistics-for-data-science/

**Comment by RafaelDavisH** [comment]
@pycoder25, quieres tomar este artículo?

**Comment by pycoder25** [comment]
Si lo puedo tomar

**Comment by pycoder25** [comment]
No se si me permita traducir este artìculo, ya que la ùltima vez que intente solo me mostraba que ya estaba asigando por otro traductor.

**Comment by pycoder25** [comment]
Hola Rafael, disculpe pero he perdido el link de Ghost, es que cambie de computadora , ¿me lo pudiera compartir? por favor
Ya deseo empezar a traducir los artículos.

**Comment by RafaelDavisH** [comment]
Hola Diego, te mando el enlace vía correo electrónico.

**Comment by pycoder25** [comment]
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/6722db2d62fb9a044255788e

**Comment by EliasPereyra** [comment]
Muchas gracias @pycoder25 por la traducción! 🚀
