### ISSUE TITLE
Learn Linux for Beginners: From Basics to Advanced Techniques [Full Book]

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#395]
https://www.freecodecamp.org/news/learn-linux-for-beginners-book-basic-to-advanced/

**Comment by RafaelDavisH** [comment]
¡Casi 30k palabras traducidas! Muchas gracias por traducir este libro completo @EliasPereyra 🚀

**Comment by EliasPereyra** [comment]
@RafaelDavisH muchas gracias, ha sido un verdadero placer, traducirlo es un excelente libro! 🚀
