### ISSUE TITLE
How to Filter an Array in JavaScript – JS Filtering for Arrays and Objects

### ISSUE THREAD

**Issue by RafaelDavisH** [freeCodeCamp/news-translation-tasks#489]
https://www.freecodecamp.org/news/filter-arrays-in-javascript/

**Comment by geekcoty** [comment]
https://www.freecodecamp.org/espanol/news/ghost/#/editor/post/67324db3296a1703fde9bce2

**Comment by EliasPereyra** [comment]
Muchas gracias @geekcoty por la traducción! 🚀
