### ISSUE TITLE
The original URL is not the article url in  freeCodeCamp

### ISSUE THREAD

**Issue by luojiyin1987** [freeCodeCamp/news-translation-tasks#540]
In  this [issue](https://github.com/freeCodeCamp/news-translation-tasks/issues/413) ,  Original URL  is a github  url, not a  freeCodeCamp web site URL,   people  need   get the originalURL  from article markdown file. 

![Image](https://github.com/user-attachments/assets/fb4e4fbf-271a-427a-9cfc-ca03381e6317)

**Comment by miyaliu666** [comment]
I checked some issues I created on August 19 and found that, as @luojiyin1987 said, their `Original URLs` point to GitHub URLs, showing "Not Found". The action running logs are gone.

I thought the cause might be there is a `.` or `-` in their titles. Then I created another two issues with those punctuations in titles, but the `Original URL` points to the original article.

Do you have any idea? @sidemt

**Comment by miyaliu666** [comment]
Thanks for the update, Yoko. So I'll revise the URLs manually. Thank you for pointing that out @luojiyin1987
